import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // pilih sesuai kebutuhan
});

export const metadata: Metadata = {
  title: "Vyolet.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${nunito.className} antialiased bg-black`}
      >
         <Providers>{children}</Providers>
          <Toaster/>
      </body>
    </html>
  );
}
